### ISSUE TITLE
Documentation how to configure on nextcloud

### ISSUE THREAD

**Issue by pablocarreraest** [RocketChat/rocketchat_nextcloud#10]
Hi, I'm new rocketchat...

I'm using nextcloud for some time with Talk (chat & video).

I saw a FOSS publication of RocketChat [(link)](https://news.itsfoss.com/rocket-chat-nextcloud-collaboration/)

I want to try but I get block on the part of configuration at Nextcloud > Settings > Rocketchat

Where do I find "Admin user ID", "Admin Token"? 
There is a good guide you can give me to point me in the right direction how setup?

**Comment by pierrelocus** [comment]
Hi @pablocarreraest ,
Thanks contacting us, I'll be happy to help :)

About the tokens, when you go in your Rocket Chat instance as Administrator, you can click on your avatar (top left), then navigate to My Account, then Personal Access Tokens.
There you can create a new pair of userId/token.

Attention, save them somewhere, they are listed there but you won't be able to get them back (like, clicking on the line doesn't open a popup with the values or so.. :) )

Hope it's clear !
Do not hesitate if you have other questions.

**Comment by pablocarreraest** [comment]
Thanks for the response @pierrelocus :)

> About the tokens, when you go in your Rocket Chat instance as Administrator, you can click on your avatar (top left), then navigate to My Account, then Personal Access Tokens.
There you can create a new pair of userId/token.

OH! there is the problem don't have Rocket Chat instance... I just download the plugin for Nextcloud app store.
So I have to install a instance on my server for sure. Just another question if may I:

Currently I work with Rocky Linux (new CentOS community version) what should go for install the version from RHEL or from CentOS?

Thanks again your response :)

**Comment by pierrelocus** [comment]
Hey @pablocarreraest , no problem !

I'd say if you're familiar with Docker, you can go with it.
Else you can find how to install RC in any distro here : https://rocket.chat/install

I'm not really into CentOS or RedHat, very used to debian based distros, so I can't really tell you what's best :)
