### ISSUE TITLE
extracting error 

### ISSUE THREAD

**Issue by xenical1212** [RocketChat/rocketchat_nextcloud#14]
I get this error when i try to download and install rocket.chat. ``Could not extract app rocketchat_nextcloud: Out-of-path file extraction {/volume4/@tmp/oc_tmp_u7ktM6-folder/rocketchat_nextcloud/vendor/bin/phpunit --> ../phpunit/phpunit/phpunit}``

**Comment by ruvenss** [comment]
Was this using the installation from the App Store or did you just download the latest release?

**Comment by ruvenss** [comment]
Disable and delete the App again and be sure that the version 0.9.6 appears in the store

**Comment by xenical1212** [comment]
it looks like it isnt updated within the nextcloud store because it says version 0.9.5rc

**Comment by ruvenss** [comment]
Now its 0.9.7
