### ISSUE TITLE
There was an issue connecting to NextCloud

### ISSUE THREAD

**Issue by tim-tation** [RocketChat/rocketchat_nextcloud#16]
Hey everybody,

first of all heads up for this extension! We both love rocket.chat and nextcloud and are really looking forward to this new user experience. Nevertheless I'm getting stuck while connection our rocket.chat instance with our cextcloud server.

I added the CREATE_TOKENS_FOR_USERS=true in the docker-compose.yml under environment, but when I'm trying to log into rocket.chat through the nextcloud settings, I'm always getting this error:

There was an issue connecting to NextCloud, please report it to https://github.com/RocketChat/nextcloud/

No other informations. What can I do? :/
Thanks for your help!

**Comment by DouglasMarketingGroup** [comment]
Hi tim-tation, I just tryed to connect my Rocket chat instance to NextCloud in the settings and I am getting the same issue.  I hope someone responds soon.

**Comment by ruvenss** [comment]
Hi Tim a new update in the appstore has been released, 0.9.7
another good way to do it is following the instructions video that we published on youtube [https://youtu.be/AshE2uG87GE](https://youtu.be/AshE2uG87GE)

**Comment by ruvenss** [comment]
There is a key element in the admin panel to allow iframes to send and receive data, by default is turned off check the video in the section of setting rocket.chat
