### ISSUE TITLE
There was an issue connecting to NextCloud

### ISSUE THREAD

**Issue by gitwittidbit** [RocketChat/rocketchat_nextcloud#17]
Trying to connect Nextcloud and Rocketchat.

I tried:

- "Administration -> General -> Options to X-Frame-Options" and add your Nextcloud URL e.g. 

Here, I am not quite sure. While I did enter my Nextcloud URL, the description for this field actually says that there are two options: deny and sameorigin. Entering an URL does not seem to be foreseen. Can someone please confirm that entering a URL is still the right thing to do?

- your RocketChat server MUST have the Environment Variable "CREATE_TOKENS_FOR_USERS=true" set. In a standard installation, just add it (without double quotes, for sure) in /lib/systemd/system/rocketchat.service

My installation is in Docker via docker-compose. So I added the environment variable to my docker-compose.yml file (and for good measure I prepended "OVERWRITE_SETTINGS_".

Not sure what else I could/should do.

Has anyone gotten this integration to work yet?

Thanks

**Comment by ruvenss** [comment]
Hi @gitwittidbit there is 2 other settings in the admin regarding iframe that needs to be activated: [https://youtu.be/AshE2uG87GE](https://youtu.be/AshE2uG87GE) check the latest parts of the video to ensure that your rocket chat is being configured correctly.

Also a new version in the appstore has been released 0.9.7 be sure to be using that one

**Comment by gitwittidbit** [comment]
> Hi @gitwittidbit there is 2 other settings in the admin regarding iframe that needs to be activated: https://youtu.be/AshE2uG87GE check the latest parts of the video to ensure that your rocket chat is being configured correctly.
> 
> Also a new version in the appstore has been released 0.9.7 be sure to be using that one

Thank you, ruvenss.

I followed your video and

- disabled "Two factor authentication"
- disabled "Restrict access inside any iframe"
- enabled "Enable Send" (iframe integration)
- enabled "Enable Receive" (iframe integration)

And I changed back the setting for "Options to X-Frame-Options" where I had put my Nextcloud URL and changed it back to "sameorigin" (same setting as in your video).

Finally, I downloaded the latest version of the Rocket.Chat-App in Nextcloud (which for me is 0.9.6).

Unfortunately, the outcome hasn't changed: It takes about 30 seconds and then comes back with the error message "There was an issue connecting to NextCloud".

Is there anything else I can try?

**Comment by merzenitch** [comment]
Same for me but since the post was closed I don't know if it was resolved without a solution being given... In the doubt I reopened another one my apologies to the devs if it was not necessary

**Comment by gitwittidbit** [comment]
No, it was not resolved.

In fact, I just tried with a completely new install of NC and of RC. Using integration app 0.9.7 this time and followed instructions to the t but again no dice...

**Comment by gitwittidbit** [comment]
Yesterday I finally got this working! :)

No changes in my RC setup (which was done according to the official guidance but had failed me several times in the past). 

But with a fresh instance of NC 25.0.2 (as updating NC from 24 didn't work for me). And without any issues, this time it just connected and started showing RC inside NC (despite the fact that the integration app isn't even listed as compatible with NC 25).

Now I just need to figure out how to sync the users and/or provide a common login for the two services...
