### ISSUE TITLE
Cannot declare class OCA\RocketIntegration\AppInfo\Application

### ISSUE THREAD

**Issue by TtuxX** [RocketChat/rocketchat_nextcloud#4]
Hi there and thank you very much for this new app integration! :)

Trying to enable the app version  0.9.3, I get this error message: 

`PHP Fatal error:  Cannot declare class OCA\RocketIntegration\AppInfo\Application, because the name is already in use in /usr/local/www/nextcloud/apps/rocketchat_nextcloud/lib/AppInfo/Application.php on line 0`

Best regards

**Comment by ruvenss** [comment]
This has been fixed
