### ISSUE TITLE
Can't install RocketChat after new update 0.9.4 -- webpage states 0.9.2

### ISSUE THREAD

**Issue by geoff-scott** [RocketChat/rocketchat_nextcloud#8]
I get an error message when entering my user credentials 

As you can see, the webpage states V.0.9.2

![image](https://user-images.githubusercontent.com/71340280/156409121-fa598014-57b7-4f37-b291-cbfab7e70816.png)

However, the installed version is 0.9.4, as per nextcloud installation

![image](https://user-images.githubusercontent.com/71340280/156409419-42eefa04-8849-4cfb-8585-290a1ea78f71.png)

**Comment by pierrelocus** [comment]
Closing issue, view release 0.9.5
